export const nationalities: string[] = [
	"France",
	"Allemagne",
	"Arabie Saoudite",
	"Autriche",
	"Belgique",
	"Danemark",
	"Espagne",
	"États-Unis",
	"Italie",
	"Pays-Bas",
	"République De Corée",
	"Royaume-Uni",
	"Suède",
	"Suisse",
	"Afghanistan",
	"Afrique Du Sud",
	"Albanie",
	"Algérie",
	"Andorre",
	"Angola",
	"Anguilla",
	"Antarctique",
	"Antigua-Et-Barbuda",
	"Argentine",
	"Arménie",
	"Aruba",
	"Australie",
	"Azerbaïdjan",
	"Bahamas",
	"Bahreïn",
	"Bangladesh",
	"Barbad",
	"Belize",
	"Bermudes",
	"Bhoutan",
	"Birmanie",
	"Biélorussie",
	"Bonaire, Saint-Eustache Et Saba",
	"Bosnie-Herzégovine",
	"Botswana",
	"Brunei Darussalam",
	"Brésil",
	"Bulgarie",
	"Burkina Faso",
	"Burundi",
	"Bénin",
	"Cambodge",
	"Cameroun",
	"Canada",
	"Cap-Vert",
	"Chili",
	"Chine",
	"Chypre",
	"Colombie",
	"Comores",
	"Congo",
	"Costa Rica",
	"Croatie",
	"Cuba",
	"Curaçao",
	"Côte D'Ivoire",
	"Djibouti",
	"Dominique",
	"Estonie",
	"Fidji",
	"Finlande",
	"Fédération De Russie",
	"Gabon",
	"Gambie",
	"Ghana",
	"Gibraltar",
	"Grenade",
	"Groenland",
	"Grèce",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernesey",
	"Guinée",
	"Guinée Équatoriale",
	"Guinée-Bissau",
	"Guyana",
	"Guyane",
	"Géorgie",
	"Géorgie Du Sud-Et-Les Îles Sandwich Du Sud",
	"Haïti",
	"Honduras",
	"Hong Kong",
	"Hongrie",
	"Inde",
	"Indonésie",
	"Irak",
	"Irlande",
	"Islande",
	"Israël",
	"Jamaïque",
	"Japon",
	"Jersey",
	"Jordanie",
	"Kazakhstan",
	"Kenya",
	"Kirghizistan",
	"Kiribati",
	"Koweït",
	"Lesotho",
	"Lettonie",
	"Liban",
	"Liberia",
	"Libye",
	"Liechtenstein",
	"Lituanie",
	"Luxembourg",
	"Macao",
	"Macédoine",
	"Madagascar",
	"Malaisie",
	"Malawi",
	"Maldives",
	"Mali",
	"Malte",
	"Maroc",
	"Martinique",
	"Maurice",
	"Mauritanie",
	"Mayotte",
	"Mexique",
	"Monaco",
	"Mongolie",
	"Montserrat",
	"Monténégro",
	"Mozambique",
	"Namibie",
	"Nauru",
	"Nicaragua",
	"Niger",
	"Nigéria",
	"Niue",
	"Norvège",
	"Nouvelle-Calédonie",
	"Nouvelle-Zélande",
	"Népal",
	"Oman",
	"Ouganda",
	"Ouzbékistan",
	"Pakistan",
	"Palaos",
	"Panama",
	"Papouasie-Nouvelle-Guinée",
	"Paraguay",
	"Philippines",
	"Pitcairn",
	"Pologne",
	"Polynésie Française",
	"Porto Rico",
	"Portugal",
	"Pérou",
	"Qatar",
	"Réunion",
	"Roumanie",
	"Rwanda",
	"Sahara Occidental",
	"Saint-Christophe-et-Niévès",
	"Saint-Martin (Partie Française)",
	"Saint-Martin (Partie Néerlandaise)",
	"Saint-Pierre-Et-Miquelon",
	"Saint-Vincent-Et-Les Grenadines",
	"Sainte-Hélène",
	"Sainte-Lucie",
	"Saint-Marin",
	"Saint-Barthélemy",
	"Sao Tomé-Et-Principe",
	"Sénégal",
	"Serbie",
	"Seychelles",
	"Sierra Leone",
	"Singapour",
	"Slovaquie",
	"Slovénie",
	"Somalie",
	"Soudan",
	"Soudan Du Sud",
	"Sri Lanka",
	"Suriname",
	"Svalbard Et Jan Mayen",
	"Swaziland",
	"République Arabe Syrienne",
	"République Centrafricaine",
	"République Démocratique Du Congo",
	"République Démocratique Populaire Lao",
	"République Islamique D'Iran",
	"République De Moldavie",
	"République Dominicaine",
	"République Du Salvador",
	"République Tchèque",
	"Taïwan",
	"Tadjikistan",
	"République-Unie De Tanzanie",
	"Thaïlande",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinité-Et-Tobago",
	"Tunisie",
	"Turquie",
	"Turkménistan",
	"Îles Turks-Et-Caïcos",
	"Tuvalu",
	"Ukraine",
	"Émirats Arabes Unis",
	"Uruguay",
	"Saint-Siège (État De La Cité Du Vatican)",
	"Venezuela",
	"Viet Nam",
	"Vanuatu",
	"Wallis Et Futuna",
	"Yémen",
	"Zambie",
	"Zimbabwe"
];
