replicaCount: 1

image:
    repository: serkox/peps-backoffice
    tag: latest
    pullPolicy: Always

service:
    type: ClusterIP
    port: 8081
    targetPort: 80

ingress:
    enabled: true
    className: nginx
    host: bo.teampeps.fr

resources: {}
