replicaCount: 1

image:
    repository: serkox/peps-backoffice-1
    tag: latest
    pullPolicy: Always

service:
    type: ClusterIP
    port: 8081
    targetPort: 80

ingress:
    enabled: true
    className: nginx
    host: backoffice.2.11.47.69.nip.io

resources: {}
